spring:
  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # "jdbc:mysql://localhost:3306/seckill?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai"
    url: jdbc:mysql://localhost:3306/seckill?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 16426359
    # 连接池
    hikari:
      # 连接池名称
      pool-name: DateHikariCP
      # 最小空闲连接
      minimum-idle: 5
      # 空闲连接存货最大时间，默认600000，十分钟
      idle-timeout: 600000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，默认30000，30秒
      max-lifetime: 30000
      # 类似心跳机制，测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # redis配置
  redis:
    # redis地址
    host: 192.168.200.128
    port: 6379
    # 操作的数据库
    database: 0
    # 超时时间
    connect-timeout: 10000ms
    # 连接池设置
    lettuce:
      pool:
        # 最大连接数，默认是8
        max-active: 8
        # 最大连接阻塞时间，默认-1，不等待
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 50
        # 最小空闲连接
        min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
